Update default bamboo_db_major_engine_version to 17
Bamboo 12 does not like Postgres 14:
```
2025-11-23 23:56:11,867 INFO [performSetupDatabaseConnection_background-process] [SetupUtilityBean] Setting up database: postgresql
2025-11-23 23:56:11,867 INFO [performSetupDatabaseConnection_background-process] [SetupUtilityBean] Check if database version is supported
2025-11-23 23:56:11,897 ERROR [performSetupDatabaseConnection_background-process] [DatabaseIsSupported] Detected POSTGRESQL version [PostgreSQL] 14.18.0 (14.18), minimal supported version is 15.0.0. Bamboo doesn't support PostgreSQL version 14.18. Please check https://confluence.atlassian.com/display/BAMBOO/Supported+Platforms for more information.
2025-11-23 23:56:11,898 ERROR [performSetupDatabaseConnection_background-process] [SetupUtilityBean] Database configuration failed. Version is below the minimum supported threshold.
com.atlassian.upgrade.UpgradeException: Version is below the minimum supported threshold.
```